---
# tasks file for installing SSSD on Ubuntu
- name: linux-ad-unimaas | Ubuntu  | installing packages
  apt: name={{item}} state=present
  with_items:
  - realmd
  - sssd
  - sssd-ad
  - krb5-user
  - samba-common
  - samba-dsdb-modules
  # This is required for the ansible module epect to do the password login for realm
  - python-pexpect
